language: node_js

node_js:
  - 6
  - 8
  - 10

sudo: false

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

after_success:
 - npm run coverage
