language: node_js
node_js:
  - 0.10

before_script:
  - if [[ `uname -s` == 'Linux' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get update -q; sudo apt-get install -y libstdc++6; fi;

script:
  - npm test
  - npm run cover
